import os
import pandas as pd
import requests

class LocalLinkBaitGenerator:
    def __init__(self, ollama_endpoint="http://localhost:11434/api/generate", model="llama3", output_dir="./reports"):
        self.endpoint = ollama_endpoint
        self.model = model
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def query_llama(self, prompt, system_prompt="You are an expert Data Analyst and Content Writer."):
        """Helper to contact the local Ollama instance."""
        payload = {
            "model": self.model,
            "prompt": prompt,
            "system": system_prompt,
            "stream": False,
            "options": {
                "temperature": 0.4
            }
        }
        try:
            response = requests.post(self.endpoint, json=payload, timeout=300)
            if response.status_code == 200:
                return response.json().get("response", "No response from model.")
            else:
                return f"❌ Error: Local Llama returned status code {response.status_code}: {response.text}"
        except requests.exceptions.ConnectionError:
            return f"❌ Error: Could not connect to Ollama at {self.endpoint}."
        except Exception as e:
            return f"❌ Error: {str(e)}"

    def analyze_data_and_generate_report(self, data_file_path, report_topic, target_audience="Investors and Journalists", sample_size=50):
        """
        Reads a dataset (Excel/CSV), extracts a smaller sample (for Llama context window), 
        and uses Local Llama to write a data-driven report designed to attract backlinks.
        """
        print(f"📊 Reading data from {data_file_path}...")
        try:
            if data_file_path.endswith('.csv'):
                df = pd.read_csv(data_file_path)
            elif data_file_path.endswith('.xlsx'):
                df = pd.read_excel(data_file_path)
            else:
                return "Unsupported file format. Use CSV or XLSX."
            
            # Take a smaller sample for Llama3's context limit
            data_sample = df.head(sample_size).to_dict(orient='records')
            summary_stats = df.describe(include='all').to_string()
            
            print(f"🦙 Asking Local {self.model} to generate '{report_topic}' Data Report...")
            
            prompt = f"""
            Act as a Lead Data Analyst and SEO Content Strategist for Ritz Group (ritzgroup.co).
            We are creating a highly authoritative 'Link Bait' industry report designed to attract backlinks from journalists, news outlets, and industry blogs.
            
            Topic: {report_topic}
            Target Audience: {target_audience}
            
            Here is a statistical summary of our proprietary dataset:
            {summary_stats}
            
            Here is a very brief sample of the raw data (first {sample_size} rows):
            {data_sample}
            
            Your Task:
            Write a comprehensive, professional industry report based on this data.
            Include:
            1. An Executive Summary (TL;DR)
            2. Key Findings (3-5 bullet points perfect for journalists to quote)
            3. Detailed Analysis (Break down the trends you see in the data)
            4. Methodology Section (State that data was compiled by Ritz Group's proprietary intelligence engine)
            5. Conclusion
            
            Format strictly in professional Markdown with clear H2/H3 tags. Include placeholder text like `[Insert Chart Here]` where visual graphs should be placed contextually.
            """
            
            result_text = self.query_llama(prompt)
            
            filename = report_topic.lower().replace(" ", "_") + "_llama.md"
            output_path = os.path.join(self.output_dir, filename)
            
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(result_text)
                
            print(f"✅ Link Bait Report generated by Llama and saved to {output_path}")
            return output_path
            
        except Exception as e:
            print(f"❌ Error generating report: {e}")
            return None

if __name__ == "__main__":
    generator = LocalLinkBaitGenerator(output_dir="./link_bait_reports")
    
    # Needs a valid local dataset
    data_path = "../Source codes and Docs (Aathi)/Hierarchy/tasks/healthion_doctors.xlsx"
    topic = "The 2026 Distribution of Specialized Clinics in Target Regions"
    
    if os.path.exists(data_path):
        generator.analyze_data_and_generate_report(data_path, topic)
    else:
        print(f"Please provide a valid data path. Could not find: {data_path}")
